/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify invoice.schema.json and run npm run generate:contracts.
 */

/**
 * Calendar date in YYYY-MM-DD format.
 */
export type CalendarDate = string;
/**
 * Nullable calendar date in YYYY-MM-DD format.
 */
export type NullableCalendarDate = string | null;
/**
 * ISO 8601 instant timestamp with mandatory timezone (e.g. 2026-10-04T12:00:00.000Z or +02:00).
 */
export type InstantString = string;
/**
 * Nullable ISO 8601 instant timestamp with mandatory timezone.
 */
export type NullableInstantString = string | null;
/**
 * Lifecycle of the legal/tax document.
 */
export type InvoiceDocumentStatus = 'draft' | 'issued' | 'cancelled';
/**
 * Lifecycle of historical imported document (drafts cannot be imported with issued numbers).
 */
export type InvoiceImportDocumentStatus = 'issued' | 'cancelled';
/**
 * Stored financial settlement status (overdue is computed dynamically).
 */
export type InvoicePaymentStatus = 'unpaid' | 'partial' | 'paid';
/**
 * Standard Polish VAT tax rates.
 */
export type InvoiceVatRate = 0 | 5 | 8 | 23;
export type InvoiceCurrency = 'PLN';
export type InvoicePaymentMethod = 'transfer' | 'cash' | 'card' | 'blik' | 'other';
export type InvoicePaymentType = 'payment' | 'refund';
export type InvoicePaymentDocument = {
  _id?:
    | string
    | {
        [k: string]: unknown;
      };
  id: string;
  invoiceId: string;
  jobId: string;
  type: InvoicePaymentType;
  amountMinor: number;
  currency: InvoiceCurrency;
  paymentDate: CalendarDate;
  paymentMethod: InvoicePaymentMethod;
  sequence: number;
  reversesPaymentId?: string | null;
  idempotencyKey?: string | null;
  operationId?: string | null;
  reference?: string;
  notes?: string;
  recordedBy?: string;
  createdAt: InstantString;
};
export type InvoiceDocument = {
  _id?:
    | string
    | {
        [k: string]: unknown;
      };
  id: string;
  jobId: string;
  clientId?: string | null;
  invoiceNumber?: string | null;
  documentStatus: InvoiceDocumentStatus;
  paymentStatus: InvoicePaymentStatus;
  amountNetMinor: number;
  vatRate?: 0 | 5 | 8 | 23 | null;
  vatAmountMinor: number;
  amountGrossMinor: number;
  paidAmountMinor: number;
  remainingAmountMinor: number;
  /**
   * Legacy decimal PLN amount (amountNetMinor / 100)
   */
  amountNet?: number;
  vatAmount?: number;
  amountGross?: number;
  paidAmount?: number;
  currency: InvoiceCurrency;
  issueDate?: NullableCalendarDate;
  dueDate?: NullableCalendarDate;
  paidDate?: NullableCalendarDate;
  cancellationDate?: NullableCalendarDate;
  cancelledAt?: NullableInstantString;
  cancelReason?: string | null;
  description?: string;
  notes?: string;
  items?: InvoiceLineItem[];
  createdAt: InstantString;
  updatedAt: InstantString;
  editVersion: number;
  isActive: boolean;
} & InvoiceDocument1;
export type InvoiceDocument1 = SimplifiedInvoiceDocument | ItemizedInvoiceDocument;
export type InvoicePostPayload = {
  jobId: string;
  clientId?: string | null;
  currency?: InvoiceCurrency;
  dueDate?: CalendarDate;
  description?: string;
  notes?: string;
  amountNetMinor?: number;
  vatRate?: InvoiceVatRate;
  items?: InvoiceLineItemInput[];
} & InvoicePostPayload1;
export type InvoicePostPayload1 = SimplifiedInvoice | ItemizedInvoice;
export type InvoicePaymentPayload = {
  expectedVersion: number;
  type?: 'payment' | 'refund';
  amountMinor: number;
  paymentMethod: InvoicePaymentMethod;
  paymentDate?: CalendarDate;
  reversesPaymentId?: string | null;
  reference?: string;
  notes?: string;
};
export type InvoicePatchPayload = {
  expectedVersion: number;
  clientId?: string | null;
  dueDate?: CalendarDate;
  description?: string;
  notes?: string;
  amountNetMinor?: number;
  vatRate?: InvoiceVatRate;
  items?: InvoiceLineItemInput[];
} & InvoicePatchPayload1;
export type InvoicePatchPayload1 = MetadataOnlyPatch | SimplifiedPatch | ItemizedPatch;
/**
 * Patch without changing amounts or items, requires at least one mutable field
 */
export type MetadataOnlyPatch = {
  [k: string]: unknown;
};
export type InvoiceBatchImportPaymentItem = {
  id: string;
  type: InvoicePaymentType;
  amountMinor: number;
  paymentDate: CalendarDate;
  paymentMethod: InvoicePaymentMethod;
  sequence: number;
  reversesPaymentId?: string | null;
  operationId?: string | null;
  reference?: string;
  notes?: string;
};
export type InvoiceBatchImportItem = {
  id: string;
  jobId: string;
  clientId?: string | null;
  invoiceNumber: string;
  documentStatus: InvoiceImportDocumentStatus;
  currency?: InvoiceCurrency;
  issueDate: CalendarDate;
  dueDate?: NullableCalendarDate;
  cancellationDate?: NullableCalendarDate;
  cancelledAt?: NullableInstantString;
  cancelReason?: string | null;
  description?: string;
  notes?: string;
  amountNetMinor?: number;
  vatRate?: InvoiceVatRate;
  items?: InvoiceLineItemInput[];
  payments?: InvoiceBatchImportPaymentItem[];
  createdAt?: NullableInstantString;
  updatedAt?: NullableInstantString;
  editVersion?: number;
  isActive?: boolean;
} & InvoiceBatchImportItem1;
export type InvoiceBatchImportItem1 = SimplifiedImportItem | ItemizedImportItem;

export interface InvoiceRoot {
  CalendarDate?: CalendarDate;
  NullableCalendarDate?: NullableCalendarDate;
  InstantString?: InstantString;
  NullableInstantString?: NullableInstantString;
  InvoiceDocumentStatus?: InvoiceDocumentStatus;
  InvoiceImportDocumentStatus?: InvoiceImportDocumentStatus;
  InvoicePaymentStatus?: InvoicePaymentStatus;
  InvoiceVatRate?: InvoiceVatRate;
  InvoiceCurrency?: InvoiceCurrency;
  InvoicePaymentMethod?: InvoicePaymentMethod;
  InvoicePaymentType?: InvoicePaymentType;
  InvoiceLineItemInput?: InvoiceLineItemInput;
  InvoiceLineItem?: InvoiceLineItem;
  InvoicePaymentDocument?: InvoicePaymentDocument;
  InvoiceDocument?: InvoiceDocument;
  InvoicePostPayload?: InvoicePostPayload;
  InvoiceIssuePayload?: InvoiceIssuePayload;
  InvoicePaymentPayload?: InvoicePaymentPayload;
  InvoiceCancelPayload?: InvoiceCancelPayload;
  InvoicePatchPayload?: InvoicePatchPayload;
  InvoiceBatchImportPaymentItem?: InvoiceBatchImportPaymentItem;
  InvoiceBatchImportItem?: InvoiceBatchImportItem;
  InvoiceBatchImportPayload?: InvoiceBatchImportPayload;
  [k: string]: unknown;
}
export interface InvoiceLineItemInput {
  id?: string;
  description: string;
  quantity: number;
  unit?: string;
  unitNetMinor: number;
  vatRate: InvoiceVatRate;
}
export interface InvoiceLineItem {
  id?: string;
  description: string;
  quantity: number;
  unit?: string;
  unitNetMinor: number;
  vatRate: InvoiceVatRate;
  amountNetMinor: number;
  vatAmountMinor: number;
  amountGrossMinor: number;
}
/**
 * Simplified invoice without line items: requires single header vatRate
 */
export interface SimplifiedInvoiceDocument {
  vatRate: InvoiceVatRate;
  /**
   * @maxItems 0
   */
  items?: [];
  [k: string]: unknown;
}
/**
 * Itemized invoice with line items: header vatRate must be null and VAT comes from items
 */
export interface ItemizedInvoiceDocument {
  vatRate: null;
  /**
   * @minItems 1
   */
  items: [unknown, ...unknown[]];
  [k: string]: unknown;
}
/**
 * Simplified invoice with header net amount and vat rate, without line items
 */
export interface SimplifiedInvoice {
  /**
   * @maxItems 0
   */
  items?: [];
  [k: string]: unknown;
}
/**
 * Itemized invoice with line items, where totals are backend-calculated
 */
export interface ItemizedInvoice {
  /**
   * @minItems 1
   */
  items: [unknown, ...unknown[]];
  [k: string]: unknown;
}
export interface InvoiceIssuePayload {
  expectedVersion: number;
  /**
   * Calendar date in YYYY-MM-DD format.
   */
  issueDate?: string;
  dueDate?: CalendarDate;
}
export interface InvoiceCancelPayload {
  expectedVersion: number;
  reason: string;
  cancellationDate?: CalendarDate;
}
/**
 * Patch amounts with header net and vat rate
 */
export interface SimplifiedPatch {
  /**
   * @maxItems 0
   */
  items?: [];
  [k: string]: unknown;
}
/**
 * Patch amounts with line items
 */
export interface ItemizedPatch {
  /**
   * @minItems 1
   */
  items: [unknown, ...unknown[]];
  [k: string]: unknown;
}
export interface SimplifiedImportItem {
  /**
   * @maxItems 0
   */
  items?: [];
  [k: string]: unknown;
}
export interface ItemizedImportItem {
  /**
   * @minItems 1
   */
  items: [unknown, ...unknown[]];
  [k: string]: unknown;
}
export interface InvoiceBatchImportPayload {
  /**
   * @minItems 1
   */
  items: [InvoiceBatchImportItem, ...InvoiceBatchImportItem[]];
}
