/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify job.schema.json and run npm run generate:contracts.
 */

export type JobStatus = 'draft' | 'planned' | 'in_progress' | 'paused' | 'done' | 'cancelled';
export type JobStageStatus = 'planowany' | 'w_toku' | 'zakończony' | 'anulowany';
export type JobStageType = 'podstawowy' | 'dodatkowy';
export type JobBillingType = 'hourly' | 'fixed' | 'm2' | 'mb';
export type JobRiskFlag = 'none' | 'delay' | 'overbudget' | 'scope_change';
export type JobPriority = 'low' | 'normal' | 'high';

/**
 * Unified JSON schema for Job domain entity, POST/PATCH payloads, batch imports, stage lifecycle, and paginated responses.
 */
export interface JobRoot {
  JobStatus?: JobStatus;
  JobStageStatus?: JobStageStatus;
  JobStageType?: JobStageType;
  JobBillingType?: JobBillingType;
  JobRiskFlag?: JobRiskFlag;
  JobPriority?: JobPriority;
  JobStage?: JobStage;
  JobStagePostPayload?: JobStagePostPayload;
  JobPostPayload?: JobPostPayload;
  JobPatchPayload?: JobPatchPayload;
  JobBatchImportPayload?: JobBatchImportPayload;
  PaginationMetadata?: PaginationMetadata;
  Job?: Job;
  JobPaginatedResponse?: JobPaginatedResponse;
  [k: string]: unknown;
}
export interface JobStage {
  id: string;
  jobId?: string;
  name: string;
  type: JobStageType;
  status: JobStageStatus;
  plannedRevenueNet: number;
  plannedCostNet?: number;
  actualRevenueNet?: number;
  actualCostNet?: number;
  revenueSharePercent?: number;
  startPlanned?: string;
  endPlanned?: string;
  startActual?: string;
  endActual?: string;
  description?: string;
  plannedLaborHours?: number;
  assignedTeams?: string[];
  assignedStartTime?: string;
  assignedLocation?: string;
  assignedNotes?: string;
  billingType?: JobBillingType;
  billingRate?: number;
  plannedLaborCost?: number;
  actualLaborHours?: number;
  actualLaborCost?: number;
  [k: string]: unknown;
}
export interface JobStagePostPayload {
  id?: string;
  jobId?: string;
  name: string;
  type: JobStageType;
  status: JobStageStatus;
  plannedRevenueNet: number;
  plannedCostNet?: number;
  revenueSharePercent?: number;
  startPlanned?: string;
  endPlanned?: string;
  description?: string;
  plannedLaborHours?: number;
  assignedTeams?: string[];
  billingType?: JobBillingType;
  billingRate?: number;
  plannedLaborCost?: number;
  [k: string]: unknown;
}
export interface JobPostPayload {
  id?: string;
  jobCode?: string;
  name: string;
  clientId: string;
  clientName?: string;
  offerId?: string;
  offerNumber?: string;
  sourceOfferId?: string;
  projectManager?: string;
  status?: JobStatus;
  priority?: JobPriority;
  location?: string;
  country?: string;
  notesInternal?: string;
  plannedStartDate?: string;
  plannedEndDate?: string;
  actualStartDate?: string;
  actualEndDate?: string;
  plannedWorkHours?: number;
  plannedTeam?: string[];
  assignedTeams?: string[];
  materialsPlannedNet?: number;
  laborPlannedNet?: number;
  logisticsPlannedNet?: number;
  equipmentPlannedNet?: number;
  otherCostsNet?: number;
  plannedTotalCost?: number;
  revenuePlannedNet?: number;
  totalPlannedRevenueNet?: number;
  totalPlannedCostNet?: number;
  marginPlannedPercent?: number;
  plannedLaborHours?: number;
  plannedLaborCost?: number;
  riskFlag?: JobRiskFlag;
  riskComment?: string;
  stages?: JobStagePostPayload[];
  allocations?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface JobPatchPayload {
  jobCode?: string;
  name?: string;
  clientId?: string;
  clientName?: string;
  offerId?: string;
  offerNumber?: string;
  sourceOfferId?: string;
  projectManager?: string;
  status?: JobStatus;
  priority?: JobPriority;
  location?: string;
  country?: string;
  notesInternal?: string;
  plannedStartDate?: string;
  plannedEndDate?: string;
  actualStartDate?: string;
  actualEndDate?: string;
  plannedWorkHours?: number;
  plannedTeam?: string[];
  assignedTeams?: string[];
  materialsPlannedNet?: number;
  laborPlannedNet?: number;
  logisticsPlannedNet?: number;
  equipmentPlannedNet?: number;
  otherCostsNet?: number;
  plannedTotalCost?: number;
  revenuePlannedNet?: number;
  totalPlannedRevenueNet?: number;
  totalPlannedCostNet?: number;
  marginPlannedPercent?: number;
  plannedLaborHours?: number;
  plannedLaborCost?: number;
  riskFlag?: JobRiskFlag;
  riskComment?: string;
  stages?: JobStagePostPayload[];
  [k: string]: unknown;
}
export interface JobBatchImportPayload {
  /**
   * @minItems 1
   * @maxItems 1000
   */
  items: [JobPostPayload, ...JobPostPayload[]];
}
export interface PaginationMetadata {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasMore: boolean;
}
export interface Job {
  id: string;
  jobCode: string;
  name: string;
  clientId: string;
  clientName?: string;
  offerId?: string;
  offerNumber?: string;
  sourceOfferId?: string;
  projectManager?: string;
  status: JobStatus;
  priority?: JobPriority;
  location?: string;
  country?: string;
  notesInternal?: string;
  plannedStartDate?: string;
  plannedEndDate?: string;
  actualStartDate?: string;
  actualEndDate?: string;
  plannedWorkHours?: number;
  plannedTeam?: string[];
  assignedTeams?: string[];
  materialsPlannedNet?: number;
  materialsActualNet?: number;
  laborPlannedNet?: number;
  laborActualNet?: number;
  logisticsPlannedNet?: number;
  logisticsActualNet?: number;
  equipmentPlannedNet?: number;
  equipmentActualNet?: number;
  otherCostsNet?: number;
  plannedTotalCost?: number;
  actualTotalCost?: number;
  revenuePlannedNet?: number;
  revenueActualNet?: number;
  actualRevenue?: number;
  marginPlannedPercent?: number;
  marginActualPercent?: number;
  riskFlag?: JobRiskFlag;
  riskComment?: string;
  timeEntriesCount?: number;
  timeEntriesHours?: number;
  plannedLaborHours?: number;
  plannedLaborCost?: number;
  actualLaborHours?: number;
  actualLaborCost?: number;
  settledLaborCost?: number;
  stages?: JobStage[];
  createdAt?: string;
  updatedAt?: string;
  [k: string]: unknown;
}
export interface JobPaginatedResponse {
  data: Job[];
  pagination: PaginationMetadata;
}
