/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify offer.schema.json and run npm run generate:contracts.
 */

export type OfferRecordKind = 'offer' | 'template';
export type OfferStatus = 'draft' | 'sent' | 'accepted' | 'rejected' | 'converted' | 'archived';
export type OfferVatRate = 0 | 8 | 23;
export type OfferDiscountType = 'none' | 'percent' | 'amount';

/**
 * Unified JSON schema for Offer domain entity, templates, POST/PATCH payloads, batch imports, and CAS concurrency control.
 */
export interface OfferRoot {
  OfferRecordKind?: OfferRecordKind;
  OfferStatus?: OfferStatus;
  OfferVatRate?: OfferVatRate;
  OfferDiscountType?: OfferDiscountType;
  RentalItem?: RentalItem;
  OfferCostBreakdown?: OfferCostBreakdown;
  OfferDocument?: OfferDocument;
  OfferPostPayload?: OfferPostPayload;
  OfferPatchPayload?: OfferPatchPayload;
  OfferBatchImportPayload?: OfferBatchImportPayload;
  OfferBatchImportItem?: OfferBatchImportItem;
  [k: string]: unknown;
}
export interface RentalItem {
  id?: string;
  name: string;
  unit?: string;
  quantity: number;
  duration: number;
  unitPrice: number;
  totalPrice: number;
  [k: string]: unknown;
}
export interface OfferCostBreakdown {
  material_cost?: number;
  assembly_cost?: number;
  transport_cost?: number;
  equipment_rental_cost?: number;
}
export interface OfferDocument {
  id: string;
  number: string;
  recordKind: OfferRecordKind;
  clientId?: string | null;
  location?: string;
  status: OfferStatus;
  createdAt: string;
  updatedAt: string;
  validUntil?: string;
  materialsCost?: number;
  laborCost?: number;
  totalCost?: number;
  totalNet?: number;
  subtotalNet?: number;
  discountAmount?: number;
  vatAmount?: number;
  totalGross?: number;
  vatRate?: OfferVatRate;
  discountType?: OfferDiscountType;
  discountValue?: number;
  rentalItems?: RentalItem[];
  costBreakdown?: OfferCostBreakdown;
  settings?: {
    [k: string]: unknown;
  };
  title?: string;
  scopeOfWork?: unknown[];
  customMaterials?: {
    [k: string]: unknown;
  };
  notes?: unknown[];
  printLayout?: string;
  printMode?: string;
  offerTemplateType?: string;
  editVersion?: number;
  isActive?: boolean;
  [k: string]: unknown;
}
export interface OfferPostPayload {
  id?: string;
  number?: string;
  recordKind?: OfferRecordKind;
  clientId?: string | null;
  location?: string;
  status?: OfferStatus;
  validUntil?: string;
  materialsCost?: number;
  laborCost?: number;
  totalCost?: number;
  totalNet?: number;
  subtotalNet?: number;
  discountAmount?: number;
  vatAmount?: number;
  totalGross?: number;
  vatRate?: OfferVatRate;
  discountType?: OfferDiscountType;
  discountValue?: number;
  rentalItems?: RentalItem[];
  costBreakdown?: OfferCostBreakdown;
  settings?: {
    [k: string]: unknown;
  };
  title?: string;
  scopeOfWork?: unknown[];
  customMaterials?: {
    [k: string]: unknown;
  };
  notes?: unknown[];
  printLayout?: string;
  printMode?: string;
  offerTemplateType?: string;
  idempotencyKey?: string;
  [k: string]: unknown;
}
export interface OfferPatchPayload {
  expectedVersion: number;
  clientId?: string | null;
  location?: string;
  status?: OfferStatus;
  validUntil?: string;
  materialsCost?: number;
  laborCost?: number;
  totalCost?: number;
  totalNet?: number;
  subtotalNet?: number;
  discountAmount?: number;
  vatAmount?: number;
  totalGross?: number;
  vatRate?: OfferVatRate;
  discountType?: OfferDiscountType;
  discountValue?: number;
  rentalItems?: RentalItem[];
  costBreakdown?: OfferCostBreakdown;
  settings?: {
    [k: string]: unknown;
  };
  title?: string;
  scopeOfWork?: unknown[];
  customMaterials?: {
    [k: string]: unknown;
  };
  notes?: unknown[];
  printLayout?: string;
  printMode?: string;
  offerTemplateType?: string;
  [k: string]: unknown;
}
export interface OfferBatchImportPayload {
  /**
   * @minItems 1
   */
  items: [OfferBatchImportItem, ...OfferBatchImportItem[]];
}
export interface OfferBatchImportItem {
  id: string;
  number: string;
  recordKind: OfferRecordKind;
  status: OfferStatus;
  clientId?: string | null;
  location?: string;
  validUntil?: string;
  materialsCost?: number;
  laborCost?: number;
  totalCost?: number;
  totalNet?: number;
  subtotalNet?: number;
  discountAmount?: number;
  vatAmount?: number;
  totalGross?: number;
  vatRate?: OfferVatRate;
  discountType?: OfferDiscountType;
  discountValue?: number;
  rentalItems?: RentalItem[];
  costBreakdown?: OfferCostBreakdown;
  settings?: {
    [k: string]: unknown;
  };
  title?: string;
  scopeOfWork?: unknown[];
  customMaterials?: {
    [k: string]: unknown;
  };
  notes?: unknown[];
  printLayout?: string;
  printMode?: string;
  offerTemplateType?: string;
  editVersion?: number;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
