/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify timeEntry.schema.json and run npm run generate:contracts.
 */

export type TimeEntryStatus =
  | 'draft'
  | 'pending'
  | 'submitted'
  | 'approved'
  | 'rejected'
  | 'foreman_approved'
  | 'foreman_rejected'
  | 'admin_approved'
  | 'admin_rejected';
export type WorkerAllowedStatus = 'draft' | 'pending' | 'submitted';
export type ForemanAllowedStatus = 'draft' | 'pending' | 'submitted' | 'foreman_approved' | 'foreman_rejected';
export type BillingType = 'hourly' | 'daily' | 'project' | 'fixed' | 'm2' | 'mb';
export type TimeEntryType = 'drive' | 'work' | 'other' | 'employee' | 'subcontractor';
export type ActivityType = 'drive' | 'work' | 'other';
export type WorkerType = 'employee' | 'subcontractor';
export type CanonicalTimeEntryPostPayload = TimeEntryPostBase & {
  employeeId: string;
  jobId: string;
  [k: string]: unknown;
};
export type TimeEntryPostPayload =
  | (TimeEntryPostBase & {
      employeeId: string;
      jobId: string;
      [k: string]: unknown;
    })
  | (TimeEntryPostBase & {
      employee_id: string;
      jobId: string;
      [k: string]: unknown;
    })
  | (TimeEntryPostBase & {
      employeeId: string;
      project_id: string;
      [k: string]: unknown;
    })
  | (TimeEntryPostBase & {
      employee_id: string;
      project_id: string;
      [k: string]: unknown;
    });

/**
 * Canonical domain contract and JSON Schemas for TimeEntry, statuses, and API payloads.
 */
export interface TimeEntryRoot {
  TimeEntryStatus?: TimeEntryStatus;
  WorkerAllowedStatus?: WorkerAllowedStatus;
  ForemanAllowedStatus?: ForemanAllowedStatus;
  BillingType?: BillingType;
  TimeEntryType?: TimeEntryType;
  TimeEntry?: TimeEntry;
  TimeEntryPostBase?: TimeEntryPostBase;
  CanonicalTimeEntryPostPayload?: CanonicalTimeEntryPostPayload;
  TimeEntryPostPayload?: TimeEntryPostPayload;
  TimeEntryPatchPayload?: TimeEntryPatchPayload;
  TimeEntryBatchImportPayload?: TimeEntryBatchImportPayload;
  TimeEntryBatchImportResult?: TimeEntryBatchImportResult;
  ActivityType?: ActivityType;
  WorkerType?: WorkerType;
  [k: string]: unknown;
}
export interface TimeEntry {
  id: string;
  employeeId: string;
  employeeName?: string;
  jobId: string;
  jobCode: string;
  jobName: string;
  stageId: string;
  stageName: string;
  date: string;
  hours: number;
  billingType: BillingType;
  hourlyRate?: number;
  cost: number;
  description?: string;
  status: TimeEntryStatus;
  crewId?: string | null;
  foremanId?: string | null;
  foremanApprovedAt?: string | null;
  adminId?: string | null;
  adminApprovedAt?: string | null;
  settlementId?: string | null;
  type?: TimeEntryType;
  workType?: string;
  quantity?: number;
  rate?: number;
  approved?: boolean;
  createdAt: string;
  updatedAt: string;
  activityType?: ActivityType;
  workerType?: WorkerType;
  [k: string]: unknown;
}
export interface TimeEntryPostBase {
  id?: string;
  jobCode?: string;
  jobName?: string;
  stageId?: string;
  stageName?: string;
  date?: string;
  hours?: number;
  billingType?: BillingType;
  hourlyRate?: number;
  cost?: number;
  description?: string;
  status?: TimeEntryStatus;
  crewId?: string | null;
  foremanId?: string | null;
  foremanApprovedAt?: string | null;
  adminId?: string | null;
  adminApprovedAt?: string | null;
  settlementId?: string | null;
  type?: TimeEntryType;
  workType?: string;
  quantity?: number;
  rate?: number;
  activityType?: ActivityType;
  workerType?: WorkerType;
  [k: string]: unknown;
}
export interface TimeEntryPatchPayload {
  id?: string;
  employeeId?: string;
  employee_id?: string;
  jobId?: string;
  project_id?: string;
  jobCode?: string;
  jobName?: string;
  stageId?: string;
  stageName?: string;
  date?: string;
  hours?: number;
  billingType?: BillingType;
  hourlyRate?: number;
  cost?: number;
  description?: string;
  status?: TimeEntryStatus;
  crewId?: string | null;
  foremanId?: string | null;
  foremanApprovedAt?: string | null;
  adminId?: string | null;
  adminApprovedAt?: string | null;
  settlementId?: string | null;
  type?: TimeEntryType;
  workType?: string;
  quantity?: number;
  rate?: number;
  _lastUpdatedAt?: string;
  activityType?: ActivityType;
  workerType?: WorkerType;
  [k: string]: unknown;
}
export interface TimeEntryBatchImportPayload {
  items: TimeEntryPostPayload[];
  [k: string]: unknown;
}
export interface TimeEntryBatchImportResult {
  status: 'success' | 'partial_success' | 'failed';
  succeeded: number;
  upserted?: number;
  modified?: number;
  matched?: number;
  failed: number;
  succeededIds: string[];
  failedIds: string[];
  errors: string[];
  [k: string]: unknown;
}
